config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  namespace :public do
    get 'homes/top'
    get 'homes/about'
    
  end
  

 # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  namespace :public do
    root to: "homes#top"
    post 'orders/comfirm'
    get 'orders/complete'
    get 'customers/unsubscribe'
    patch 'customers/withdraw' =>'customers#withdraw'
    delete 'cart_items/destroy_all'

    resources :items,only:[:index,:show]
    resources :customers,only:[:show,:edit,:update]
    resources :cart_items,only:[:index,:update,:destroy,:create]
    resources :addresses,only:[:index,:edit,:create,:update,:destroy]
    resources :orders,only:[:new,:create,:index,:show] 
 
  end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
    root to: 'homes#top'
    resources :genres,only:[:index,:create,:edit,:update ]
    resources :items,only:[:index,:new,:create,:show,:edit,:update]
    resources :customers,only:[:index,:show,:edit,:update]
    resources :orders,only:[:show,:update]
    resources :order_details,only:[:update] 
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
 belongs_to :customer
 
 validates :customer_id,presence: true
 validates :name,presence: true
 validates :postal_code,presence: true
 validates :address,presence: true
 
 def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
 end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validate :last_name
  validate :first_name
  validate :last_name_kana
  validate :first_name_kana
  validate :postal_code
  validate :address 
  validate :telephone_number
  validates :is_deleted, inclusion: { in: [true,false] }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
belongs_to :item
belongs_to :customer

validates :item_id,presence: true
validates :customer_id,presence: true
validates :amount,presence: true


def subtotal
    item.with_tax_price * amount
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates:last_name,presence: true
  validates :first_name,presence: true
  validates :last_name_kana,presence: true
  validates :first_name_kana,presence: true
  validates :postal_code,presence: true
  validates :address,presence: true
  validates :telephone_number,presence: true
  validates :is_deleted, inclusion: { in: [true,false] }
  
  def full_name
    self.last_name + self.first_name
  end 
 
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items, dependent: :destroy 
  validates :name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord
 has_one_attached :image 
 belongs_to :genre
 has_many :cart_items, dependent: :destroy
 has_many :order_details, dependent: :destroy 
 
 
 validates :name, presence: true
 validates :introduction,presence: true
 validates :genre_id,presence:true
 validates :price,presence:true 
 validates :is_active, inclusion: { in: [true, false] }
 
def with_tax_price
    (price * 1.1).floor
end

end

app/models/order.rb
class Order < ApplicationRecord
belongs_to :customer
has_many :order_details, dependent: :destroy 

validates :customer_id,presence: true
validates :postal_code,presence: true
validates :address,presence: true
validates :name,presence: true
validates :shipping_cost,presence: true
validates :total_payment,presence: true
 
enum payment_method: { credit_card: 0, transfer: 1 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
belongs_to :item 
belongs_to :order

validates :item_id,presence: true
validates :order_id,presence: true
validates :price,presence: true
validates :amount,presence: true
end
 

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!,only: [:show,:edit,:update,:index]

  def index
    @customers = Customer.all
    
  end

  def show
    @customer = Customer.find(params[:id])
  end 

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
  @customer = Customer.find(params[:id])
   if @customer.update(customer_params) 
   redirect_to admin_customer_path(@customer.id)
   else
   render :edit 
   end 
  end 
  
  private
  
  def customer_params
   params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,
   :telephone_number,:is_deleted) 
  end

end 

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
 before_action :authenticate_admin!,only: [:create,:edit,:update,:index]

    
 def index
  @genre = Genre.new
  @genres = Genre.all
 end
 
 def create
  @genre = Genre.new(genre_params)
  if @genre.save
  redirect_to admin_genres_path
  else
  redirect_to admin_genres_path  
  end
 end
 
 def edit
  @genre = Genre.find(params[:id])
 end
 
 def update
  @genre = Genre.find(params[:id])
  if @genre.update(genre_params)
  redirect_to admin_genres_path
  else 
  render :edit
  end 
 end
 

 private
 def genre_params
   params.require(:genre).permit(:name)
 end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top 
    @orders = Order.all
  end 
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
 before_action :authenticate_admin!,only: [:create,:edit,:update,:index, :show, :new]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end
  
  def create
   @item = Item.new(item_params)
   if @item.save
    redirect_to admin_item_path(@item.id)
   else 
    render :new
   end
  end
   
  def show
   @item = Item.find(params[:id])
  end

  def edit
   @item = Item.find(params[:id])
  end
  
  def update
   @item = Item.find(params[:id])
   if @item.update(item_params) 
   redirect_to admin_item_path(@item.id)
   else 
   render :edit
   end
  end
  
  private
  
  def item_params
   params.require(:item).permit(:name,:image,:introduction,:genre_id,:price,:is_active) 
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def show
    @order = Order.find(params[:id])
  end 

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    





    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
    end
end 

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
 <div class="container">
  <div class="row">
   <div class="col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h2><%= @customer.full_name  %>さんの会員情報編集</h2>
 
<% if @customer.errors.any? %>
  <%= @customer.errors.count %>件のエラーが発生しました
  <ul>
    <% @customer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %> 
  </ul>
<% end %>

 <label for="id">会員ID</label>
 <%= @customer.id %> 

<%= form_with model: @customer, url: admin_customer_path do |f| %>

 <label>名前</label><br>
<th>(姓)</th><%= f.text_field :last_name,autoforcus: true,  placeholder: "令和" %>
<th>(姓)</th><%= f.text_field :first_name,autofocus: true, placeholder: "道子" %></br>

<label>カナ</label><br> 
<th>(セイ)</th><%= f.text_field :last_name_kana,autofocus: true, placeholder: "レイワ" %>
<th>(メイ)</th><%= f.text_field :first_name_kana,autofocus: true, placeholder: "ミチコ" %><br> 

  <div class="field"> 
    <%= f.label :メールアドレス %>
    <%= f.email_field :email, autofocus: true, placeholder: "sample@example.com" %>
  </div>

    <%= f.label :郵便番号 %>
    <em>(ハイフンなし)
    <%= f.text_field :postal_code, autofocus: true, placeholder: "0000000" %></br>

    <%= f.label :住所 %>
    <%= f.text_field :address, autofocus: true, placeholder: "東京都渋谷区◯◯町0-0" %></br>
    
    <%= f.label :電話番号 %>
    <em>(ハイフンなし)
    <%= f.text_field :telephone_number, autofocus: true, placeholder: "00000000000" %>

<h4>会員ステータス</h4>
      <%= f.radio_button :is_deleted, true %> 
      <%= f.label :is_deleted, '退会', value: true %>
      <%= f.radio_button :is_deleted, false %>
      <%= f.label :is_deleted, '有効', value: false %><br/>



  <div class="actions">
    <%= f.submit "変更を保存"  %>
  </div>
<% end %>

  </div>
 </div>
</div>

 

app/views/admin/customers/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h2>会員一覧</h2>

<table class="table table-striped bg-light">
<tr>
<th>会員ID</th>
<th>氏名</th>
<th>メールアドレス</th>
<th>ステータス</th>
</tr>

<% @customers.each do |customer| %><br/> 
<tr>
 <th><%= customer.id %></th>
 
 <th><%= link_to customer.full_name,admin_customer_path(customer.id) %></th>


 <th><%= customer.email %></th>
 
 <th><% if customer.is_deleted == false %>
  有効
 <% else %>
  退会 
 <% end %>
<% end %></th>
</tr>

</table>
  </div>
 </div>
</div>

app/views/admin/customers/show.html.erb
 <div class="container">
  <div class="row">
   <div class="col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

 
 <h2><%= @customer.last_name + "" + @customer.first_name %>さんの会員詳細</h2> 
 
  <label for="id">会員ID</label> 
  <%= @customer.id %><br> 
 
  <label for="name">氏名</label> 
　<%= @customer.last_name + "" + @customer.first_name %><br>

  <label for="kana">フリガナ</label> 
  <%= @customer.last_name_kana + "" + @customer.first_name_kana %><br>

  <label for="postal">郵便番号</label>
  <%= @customer.postal_code %><br>

  <label for="address">住所</label> 
  <%= @customer.address %><br>

  <label for="telephone_number">電話番号</label>
  <%= @customer.telephone_number %><br>

  <label for="email">メールアドレス</label> 
  <%= @customer.email %><br>

<label for="is_deleted">会員ステータス</label> 
<% if @customer.is_deleted == false %> 
  有効
 <% else %> 
  退会 
 <% end %></br>
 
 <%= link_to "編集する", edit_admin_customer_path(@customer), class: 'btn btn-success' %>
 <%= link_to "注文履歴一覧を見る", admin_root_path ,class: 'btn btn-primary' %>
  
  </div>
 </div>
</div> 