config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  namespace :public do
    get 'homes/top'
    get 'homes/about'
    
  end
  

 # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  namespace :public do
    root to: "homes#top"
    post 'orders/comfirm'
    get 'orders/complete'
    get 'customers/unsubscribe'
    patch 'customers/withdraw' =>'customers#withdraw'
    delete 'cart_items/destroy_all'

    resources :items,only:[:index,:show]
    resources :customers,only:[:show,:edit,:update]
    resources :cart_items,only:[:index,:update,:destroy,:create]
    resources :addresses,only:[:index,:edit,:create,:update,:destroy]
    resources :orders,only:[:new,:create,:index,:show] 
 
  end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
    root to: 'homes#top'
    resources :genres,only:[:index,:create,:edit,:update ]
    resources :items,only:[:index,:new,:create,:show,:edit,:update]
    resources :customers,only:[:index,:show,:edit,:update]
    resources :orders,only:[:show,:update]
    resources :order_details,only:[:update] 
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
 belongs_to :customer
 
 validates :customer_id,presence: true
 validates :name,presence: true
 validates :postal_code,presence: true
 validates :address,presence: true
 
 def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
 end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validate :last_name
  validate :first_name
  validate :last_name_kana
  validate :first_name_kana
  validate :postal_code
  validate :address 
  validate :telephone_number
  validates :is_deleted, inclusion: { in: [true,false] }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
belongs_to :item
belongs_to :customer

validates :item_id,presence: true
validates :customer_id,presence: true
validates :amount,presence: true


def subtotal
    item.with_tax_price * amount
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates:last_name,presence: true
  validates :first_name,presence: true
  validates :last_name_kana,presence: true
  validates :first_name_kana,presence: true
  validates :postal_code,presence: true
  validates :address,presence: true
  validates :telephone_number,presence: true
  validates :is_deleted, inclusion: { in: [true,false] }
  
  def full_name
    self.last_name + self.first_name
  end 
 
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items, dependent: :destroy 
  validates :name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord
 has_one_attached :image 
 belongs_to :genre
 has_many :cart_items, dependent: :destroy
 has_many :order_details, dependent: :destroy 
 
 
 validates :name, presence: true
 validates :introduction,presence: true
 validates :genre_id,presence:true
 validates :price,presence:true 
 validates :is_active, inclusion: { in: [true, false] }
 
def with_tax_price
    (price * 1.1).floor
end

end

app/models/order.rb
class Order < ApplicationRecord
belongs_to :customer
has_many :order_details, dependent: :destroy 

validates :customer_id,presence: true
validates :postal_code,presence: true
validates :address,presence: true
validates :name,presence: true
validates :shipping_cost,presence: true
validates :total_payment,presence: true
 
enum payment_method: { credit_card: 0, transfer: 1 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
belongs_to :item 
belongs_to :order

validates :item_id,presence: true
validates :order_id,presence: true
validates :price,presence: true
validates :amount,presence: true
end
 

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
 before_action :authenticate_admin!,only: [:create,:edit,:update,:index]

    
 def index
  @genre = Genre.new
  @genres = Genre.all
 end
 
 def create
  @genre = Genre.new(genre_params)
  if @genre.save
  redirect_to admin_genres_path
  else
  redirect_to admin_genres_path  
  end
 end
 
 def edit
  @genre = Genre.find(params[:id])
 end
 
 def update
  @genre = Genre.find(params[:id])
  if @genre.update(genre_params)
  redirect_to admin_genres_path
  else 
  render :edit
  end 
 end
 

 private
 def genre_params
   params.require(:genre).permit(:name)
 end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top 
    @orders = Order.all
  end 
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
 before_action :authenticate_admin!,only: [:create,:edit,:update,:index, :show, :new]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end
  
  def create
   @item = Item.new(item_params)
   if @item.save
    redirect_to admin_item_path(@item.id)
   else 
    render :new
   end
  end
   
  def show
   @item = Item.find(params[:id])
  end

  def edit
   @item = Item.find(params[:id])
  end
  
  def update
   @item = Item.find(params[:id])
   if @item.update(item_params) 
   redirect_to admin_item_path(@item.id)
   else 
   render :edit
   end
  end
  
  private
  
  def item_params
   params.require(:item).permit(:name,:image,:introduction,:genre_id,:price,:is_active) 
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def show
    @order = Order.find(params[:id])
  end 

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    





    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
    end
end 

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h2>ジャンル編集</h2>
<% if @genre.errors.any? %>
  <%= @genre.errors.count %>件のエラーが発生しました
  <ul>
    <% @genre.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul> 
<% end %>
<%= form_with model: @genre, url: admin_genre_path do |f| %>

  <h4>ジャンル</h4>
  <%= f.text_field :name %>
  
  <%= f.submit '変更を保存', class: 'btn btn-success' %>
   
<% end %>

  </div>
 </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h2>ジャンル一覧、追加</h2>
<p></p> 
<% if @genre.errors.any? %>
  <%= @genre.errors.count %>件のエラーが発生しました
  <ul>
    <% @genre.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @genre ,url: admin_genres_path do |f| %>

 <label for="name">ジャンル名</label>
 <%= f.text_field :name, placeholder: 'ケーキ' %> 
 
 <%= f.submit '新規登録', class: 'btn btn-success' %>
  <% end %> 

<table class="table table-striped bg-light">
 <tr>
  <th>ジャンル</th>
  <th></th>
 </tr>
 
 <% @genres.each do |genre| %>
 <tr>
 <th><%= genre.name %></th>  
 <th><%= link_to "編集する", edit_admin_genre_path(genre.id), class: 'btn btn-success' %></th><br/>
 </tr> 
 
 <% end %>
 </table>
     </div> 
  </div> 
</div>

app/views/admin/items/edit.html.erb
<div class="container">
 <div class="row">
   <div class="col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h2>商品編集</h2>
<% if @item.errors.any? %>
  <%= @item.errors.count %>件のエラーが発生しました
  <ul>
    <% @item.errors.full_messages.each do |message| %>
      <li><%= message %></li> 
    <% end %> 
  </ul>
<% end %>
<%= form_with model: @item, url: admin_item_path do |f| %>
 
 <h4>商品画像</h4>
<%= f.file_field :image %> 

<h4>商品名</h4>
<%= f.text_field :name,placeholder: '商品名' %>

<h4>商品説明</h4>
<%= f.text_area :introduction,placeholder: 'ここに説明文を記述します' %>

<h4>ジャンル</h4>
 <%= f.collection_select :genre_id, Genre.all,:id, :name,
    include_blank: '~選択してください~' %> 
 
<h4>税抜価格</h4>
<%= f.text_field :price,placeholder: '1000' %>円

<h4>販売ステータス</h4>
      <%= f.radio_button :is_active, true %>
      <%= f.label :is_active, '販売中', value: true %>
      <%= f.radio_button :is_active, false %>
      <%= f.label :is_active, '販売停止中', value: false %><br/>
      
  <%= f.submit '変更を保存' ,class: 'btn btn-success'%>
   
<% end %>

   </div>
  </div>
 </div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
 
<h3>商品一覧</h2>
 <%= button_to "＋", {controller: 'items', action: 'new'}, {method: :get} %>
  
<table class="table table-striped bg-light">
<tr> 
 <th>商品ID</th>
 <th>商品名</th>
 <th>税抜価格</th> 
 <th>ジャンル</th> 
 <th>ステータス</th>
</tr>
<% @items.each do |item| %><br/> 
 <tr>
  <th><%= item.id %></th>
  
  <th><%= link_to item.name,admin_item_path(item.id) %></th>
  
  <th><%= item.price.to_s(:delimited, delimiter: ',') %></th>
 
  <th><%= item.genre.name %></th>
 
  <th><% if item.is_active == true %> 
         販売中
       <% else %>
         販売停止中
       <% end %><th> 
 </tr>
<% end %>
</table> 

   </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    
<h2>商品新規登録</h2>
<% if @item.errors.any? %>
  <%= @item.errors.count %>件のエラーが発生しました
  <ul>
    <% @item.errors.full_messages.each do |message| %>
      <li><%= message %></li> 
    <% end %>
  </ul>
<% end %>
<%= form_with model: @item, url: admin_items_path do |f| %> 
<div class="form-group">
 <label for="image">商品画像</label><br>
<%= f.file_field :image,accept: "image/*" %>  
</div>

<div class="form-group">
 <label for="name">商品名</label><br>
<%= f.text_field :name,placeholder: '商品名' %>
</div>

<div class="form-group">
  <label for="introduction">商品説明</label><br>
<%= f.text_area :introduction,placeholder: 'ここに説明文を記述します' %>
</div>

<div class="form-group">
  <label for="genre">ジャンル</label><br>
 <%= f.collection_select :genre_id, Genre.all,:id, :name,
    include_blank: '~選択してください~' %>
</div>

<div class="form-group">
  <label for="price">税抜価格</label><br>
<%= f.text_field :price,placeholder: '1,000' %>円
</div>

<div class="form-group">
  <label for="is_active">販売ステータス</label><br>
      <%= f.radio_button :is_active, true %> 
      <%= f.label :is_active, '販売中', value: true %>
      <%= f.radio_button :is_active, false %>
      <%= f.label :is_active, '販売停止中', value: false %><br/>
</div>

 <%= f.submit '新規登録',class: 'btn btn-success' %>
<% end %>
   </div> 
  </div>
 </div>

app/views/admin/items/show.html.erb
<div class="container">
 <div class="row">
   <div class="col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h2>商品詳細</h2>

<% if @item.image.attached? %> 
<%= image_tag @item.image ,size: "250x150" %>
<% else %>
<%= image_tag'no_image',size: "250x150" %>
<% end %><br>
 <label for="name">商品名 </label>
<%= @item.name %><br>

 <label for="introduction">商品説明 </label>
<%= @item.introduction %><br>

 <label for="genre">ジャンル </label>
<%= @item.genre.name %><br>

 <label for="price">税抜価格 </label> 
￥<%= @item.with_tax_price%>円<br>

 <label for="is_active">販売ステータス </label> 
<% if @item.is_active == true %>
販売中  
<% else %> 
販売停止中
<% end %><br>
 
<%= link_to "編集する", edit_admin_item_path(@item),class: 'btn btn-success' %>

  </diV>
 </div> 
</div> 

app/views/admin/orders/show.html.erb
 <div class="container">
  <div class="row">
   <div class="col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h2>注文履歴詳細</h2>
  <label for="name">購入者</label>
   <%= @order.customer.full_name %><br>
  <label for="created_at">注文日</label>
   <%= @order.created_at.strftime('%Y/%m/%d') %><br>
  <label for="address">配送先</label>
   <%= @order.postal_code %>
   <%= @order.address %> 
   <%= @order.name %><br>
  <label for="payment_method">支払方法</label>
   <%= @order.payment_method_i18n %> 
  
  <table class="table table-striped bg-light">
<tr>
  <th>商品名</th>
  <th>単価（税込）</th>
  <th>数量</th>
  <th>小計</th>
</tr>
  <% @subtotal = 0 %> 
  <% @order.order_details.each do |order_detail| %>
  <tr>
  <th><%= order_detail.item.name %></th>
  <th><%= order_detail.item.with_tax_price %></th>
  <th><%= order_detail.amount %></th>
  <th><%= order_detail.amount*order_detail.item.with_tax_price %></th>
 
  </tr>  
  <% end %> 
  </table>
  <% @subtotal += @order.total_payment-500 %>
 <label>送料</label>
   <td>500円</td><br>
  <label for="subtotal">商品合計</label>
  <%= @subtotal.to_s(:delimited, delimiter: ',') %><br>
  
  <label for="total_payment">請求金額合計</label>
  <%= @order.total_payment.to_s(:delimited, delimiter: ',') %>
   </div>
  </div>
</div>