config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  namespace :public do
    get 'homes/top'
    get 'homes/about'
    
  end
  

 # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  namespace :public do
    root to: "homes#top"
    post 'orders/comfirm'
    get 'orders/complete'
    get 'customers/unsubscribe'
    patch 'customers/withdraw' =>'customers#withdraw'
    delete 'cart_items/destroy_all'

    resources :items,only:[:index,:show]
    resources :customers,only:[:show,:edit,:update]
    resources :cart_items,only:[:index,:update,:destroy,:create]
    resources :addresses,only:[:index,:edit,:create,:update,:destroy]
    resources :orders,only:[:new,:create,:index,:show] 
 
  end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
    root to: 'homes#top'
    resources :genres,only:[:index,:create,:edit,:update ]
    resources :items,only:[:index,:new,:create,:show,:edit,:update]
    resources :customers,only:[:index,:show,:edit,:update]
    resources :orders,only:[:show,:update]
    resources :order_details,only:[:update] 
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
 belongs_to :customer
 
 validates :customer_id,presence: true
 validates :name,presence: true
 validates :postal_code,presence: true
 validates :address,presence: true
 
 def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
 end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validate :last_name
  validate :first_name
  validate :last_name_kana
  validate :first_name_kana
  validate :postal_code
  validate :address 
  validate :telephone_number
  validates :is_deleted, inclusion: { in: [true,false] }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
belongs_to :item
belongs_to :customer

validates :item_id,presence: true
validates :customer_id,presence: true
validates :amount,presence: true


def subtotal
    item.with_tax_price * amount
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates:last_name,presence: true
  validates :first_name,presence: true
  validates :last_name_kana,presence: true
  validates :first_name_kana,presence: true
  validates :postal_code,presence: true
  validates :address,presence: true
  validates :telephone_number,presence: true
  validates :is_deleted, inclusion: { in: [true,false] }
  
  def full_name
    self.last_name + self.first_name
  end 
 
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items, dependent: :destroy 
  validates :name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord
 has_one_attached :image 
 belongs_to :genre
 has_many :cart_items, dependent: :destroy
 has_many :order_details, dependent: :destroy 
 
 
 validates :name, presence: true
 validates :introduction,presence: true
 validates :genre_id,presence:true
 validates :price,presence:true 
 validates :is_active, inclusion: { in: [true, false] }
 
def with_tax_price
    (price * 1.1).floor
end

end

app/models/order.rb
class Order < ApplicationRecord
belongs_to :customer
has_many :order_details, dependent: :destroy 

validates :customer_id,presence: true
validates :postal_code,presence: true
validates :address,presence: true
validates :name,presence: true
validates :shipping_cost,presence: true
validates :total_payment,presence: true
 
enum payment_method: { credit_card: 0, transfer: 1 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
belongs_to :item 
belongs_to :order

validates :item_id,presence: true
validates :order_id,presence: true
validates :price,presence: true
validates :amount,presence: true
end
 

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
 before_action :authenticate_admin!,only: [:create,:edit,:update,:index]

    
 def index
  @genre = Genre.new
  @genres = Genre.all
 end
 
 def create
  @genre = Genre.new(genre_params)
  if @genre.save
  redirect_to admin_genres_path
  else
  redirect_to admin_genres_path  
  end
 end
 
 def edit
  @genre = Genre.find(params[:id])
 end
 
 def update
  @genre = Genre.find(params[:id])
  if @genre.update(genre_params)
  redirect_to admin_genres_path
  else 
  render :edit
  end 
 end
 

 private
 def genre_params
   params.require(:genre).permit(:name)
 end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top 
    @orders = Order.all
  end 
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
 before_action :authenticate_admin!,only: [:create,:edit,:update,:index, :show, :new]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end
  
  def create
   @item = Item.new(item_params)
   if @item.save
    redirect_to admin_item_path(@item.id)
   else 
    render :new
   end
  end
   
  def show
   @item = Item.find(params[:id])
  end

  def edit
   @item = Item.find(params[:id])
  end
  
  def update
   @item = Item.find(params[:id])
   if @item.update(item_params) 
   redirect_to admin_item_path(@item.id)
   else 
   render :edit
   end
  end
  
  private
  
  def item_params
   params.require(:item).permit(:name,:image,:introduction,:genre_id,:price,:is_active) 
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    





    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
    end
end 

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
     
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <body class="d-flex flex-column vh-100">
     <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light"> 
        <div class="container"> 
         <a class="navbar-brand" href="/"><span>長野CAKE</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              
          <% if customer_signed_in? %> 
          <!--顧客がログインしている時 -->
          <li class="nav-item">
           <%= link_to "マイページ", public_customer_path(current_customer),class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item">
           <%= link_to "商品一覧", public_items_path,class: 'nav-link text-dark' %> 
          </li>
          <li class="nav-item">
           <%= link_to "カート", public_cart_items_path,class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item">
           <%= link_to "About", public_homes_about_path,class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item">
           <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
          </li>
        <% elsif admin_signed_in? %> 
          <!-- 管理者がログインしている時 -->
          <li class="nav-item">
           <%= link_to "商品一覧", admin_items_path ,class: 'nav-link text-dark'%>
          </li>
          <li class="nav-item">
           <%= link_to "会員一覧", admin_customers_path,class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item">
           <%= link_to "注文履歴一覧", admin_root_path,class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item">
           <%= link_to "ジャンル一覧", admin_genres_path,class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item">
           <%= link_to "About", public_homes_about_path,class: 'nav-link text-dark'  %>
          </li>
          <li class="nav-item">
           <%= link_to "ログアウト", destroy_admin_session_path, method: :delete ,class: 'nav-link text-dark' %>
          </li>
        <% else %> 

          <!-- ログインしていない時 -->
          <li class="nav-item">
           <%= link_to "商品一覧", public_items_path,class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item">
          <%= link_to "新規登録", new_customer_registration_path,class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item">
          <%= link_to "About", public_homes_about_path,class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item">
          <%= link_to "ログイン", new_customer_session_path,class: 'nav-link text-dark' %>
          </li>
        <% end %> 
        </ul>
      </div>
    </div>
  </nav>
</header>

   <main class="mb-auto pt-5 pb-5"> 
    <%= yield %>  
   </main>
   
   <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container"> 
        <div class="row no-gutters"> 
          <div class="col-md-4"> 
          </div>
          <div class="col-md-8">
            <ul class="p-0 list-unstyled"> 
            </ul>
          </div>
        </div>
      </div> 
    </footer>
  </body>
  
</html>